# Generated by Django 5.0.6 on 2024-07-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_posts", "0003_remove_post_artist_remove_post_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(to="a_posts.tag"),
        ),
    ]
