# Generated by Django 5.0.6 on 2024-07-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a_posts", "0007_alter_comment_options_reply"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reply", old_name="parent_post", new_name="parent_comment",
        ),
    ]
