# Generated by Django 5.0.6 on 2024-07-29 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_posts", "0011_likedreply_reply_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.FileField(
                default="",
                null=True,
                upload_to="social_post_images",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["MOV", "avi", "mp4", "webm", "mkv"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="social_post_images"
            ),
        ),
    ]
