# Generated by Django 5.0.6 on 2024-08-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_posts", "0014_alter_post_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="a_posts.tag"),
        ),
    ]
