# Generated by Django 5.0.6 on 2024-07-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="a_posts/images/avatar_default.svg",
                null=True,
                upload_to="profile/",
            ),
        ),
    ]
