# Generated by Django 5.0.6 on 2024-08-03 14:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_profile", "0002_alter_profile_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="id",),
        migrations.AddField(
            model_name="profile",
            name="id_user",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
