# Generated by Django 5.0.6 on 2024-08-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a_profile", "0003_remove_profile_id_profile_id_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="id_user", new_name="id",
        ),
    ]
