# Generated by Django 5.0.6 on 2024-08-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_profile", "0004_rename_id_user_profile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.IntegerField(
                blank=True, default=None, primary_key=True, serialize=False
            ),
        ),
    ]
