# Generated by Django 5.0.6 on 2024-08-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_profile", "0005_alter_profile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
